// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package sql

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Category struct {
	ID   pgtype.UUID
	Name pgtype.Text
}

type Device struct {
	ID      string
	Name    string
	Model   string
	IpAddr  string
	MacAddr string
}

type Event struct {
	ID          pgtype.UUID
	Description pgtype.Text
	SourceAddr  pgtype.Text
	DstAddr     pgtype.Text
	Category    pgtype.Text
	EventCode   pgtype.Text
	IsOffence   pgtype.Bool
}

type Offence struct {
	ID          pgtype.UUID
	Description pgtype.Text
	SourceAddr  pgtype.Text
	DstAddr     pgtype.Text
	Category    pgtype.Text
	EventCode   pgtype.Text
}

type Rule struct {
	ID          pgtype.UUID
	Severity    pgtype.Int4
	Relevance   pgtype.Int4
	Credibility pgtype.Int4
	IsLogged    pgtype.Bool
	Category    pgtype.Text
	OfGroup     pgtype.Text
}
